version: '3'
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    env_file:
        - .env
    volumes:
      - .:/usr/src/app
    command: npm run start:dev
    ports:
      - "3000:3000"
